[tools]
rojo = { source = "rojo-rbx/rojo", version = "6.1.0" }
wally = { source = "UpliftGames/wally", version = "0.3.1" }
selene = { source = "Kampfkarren/selene", version = "x" }
stylua = { source = "JohnnyMorganz/stylua", version = "0.11.3" }